#include <FreeRTOS.h>
#include <task.h>
#include <main.h>
#include <AppMain.hpp>
#include <fatfs.h>

extern "C" void vPortSetupTimerInterrupt(void);
extern "C" int main();


HAL_StatusTypeDef HAL_InitTick(uint32_t TickPriority) {
	vPortSetupTimerInterrupt();
	return HAL_OK;
}
void HAL_IncTick(void) { Error_Handler(); }
uint32_t HAL_GetTick(void) { return (xPortIsInsideInterrupt() != pdFALSE) ? xTaskGetTickCountFromISR() : xTaskGetTickCount(); }
void HAL_Delay(uint32_t Delay) { if (xPortIsInsideInterrupt() == pdFALSE) vTaskDelay(Delay); } //todo implement spinlock or something for the case of ISR
void HAL_SuspendTick(void) { vTaskSuspendAll(); }
void HAL_ResumeTick(void) { xTaskResumeAll(); }

extern "C"
void vApplicationDaemonTaskStartupHook(void) {
	main(); // generated by CubeMX
	fatfs_Init();
	AppMain::Setup();
}

extern "C"
void vApplicationMallocFailedHook(void) {
	__asm("BKPT #0\n");
}

extern "C"
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName) {
	__asm("BKPT #0\n");
}
